export const FETCH_LIST_POKEMON_PENDING = "FETCH_LIST_POKEMON_PENDING";
export const FETCH_LIST_POKEMON_SUCCESS = "FETCH_LIST_POKEMON_SUCCESS";
export const FETCH_LIST_POKEMON_ERROR = "FETCH_LIST_POKEMON_ERROR";

export const FETCH_DETAIL_POKEMON_PENDING = "FETCH_DETAIL_POKEMON_PENDING";
export const FETCH_DETAIL_POKEMON_SUCCESS = "FETCH_DETAIL_POKEMON_SUCCESS";
export const FETCH_DETAIL_POKEMON_ERROR = "FETCH_DETAIL_POKEMON_ERROR";
